<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Win32Resource>EDEA.res</Win32Resource>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Jot" Version="2.1.17" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Material.Icons.WPF" Version="3.0.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.122" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.3" />
    <PackageReference Include="SayIt" Version="1.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EDEA.Core\EDEA.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\mc.dat" Link="mc.dat" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\gc.dat" Link="gc.dat" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
